import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, CalendarDays, Compass, MapPinned, Route, Sparkles, Wallet } from 'lucide-react'
import { DestinationCard } from '../components/DestinationCard'
import { WeatherCard } from '../components/WeatherCard'
import { destinations, interests } from '../data/destinations'
import type { Interest } from '../types'

const highlights=['burnham-park','mines-view-park','baguio-botanical-garden','camp-john-hay']
export function Home(){
  const navigate=useNavigate(),[days,setDays]=useState(2),[travelers,setTravelers]=useState(2),[budget,setBudget]=useState(5000),[selected,setSelected]=useState<Interest[]>(['Nature','Food'])
  const toggle=(v:Interest)=>setSelected(x=>x.includes(v)?x.length>1?x.filter(i=>i!==v):x:[...x,v])
  const go=()=>navigate('/planner',{state:{quick:{days,travelers,budget,interests:selected}}})
  return <>
    <section className="hero"><div className="hero-photo"/><div className="hero-shade"/><div className="container hero-content"><div className="hero-kicker"><span className="hero-dot"/> A BETTER WAY TO EXPLORE BAGUIO AND BEYOND</div><h1>Discover the highlands<br/><em>your way.</em></h1><p>Mountain mornings, café afternoons, and the stops in between. Shape a trip around your budget, interests, and pace.</p><div className="hero-actions"><Link className="button button-light" to="/planner">Plan my trip <ArrowUpRight size={18}/></Link><Link className="button button-ghost" to="/explore">Explore places <ArrowRight size={18}/></Link></div><div className="hero-foot"><span><Compass size={17}/> Curated local places</span><span><Wallet size={17}/> Clear cost estimates</span><span><MapPinned size={17}/> Easy-to-follow days</span></div></div><div className="hero-side-label">16°25′ N · 120°36′ E <span/> BAGUIO CITY, PHILIPPINES</div></section>
    <section className="container quick-section"><div className="quick-head"><div><span className="eyebrow">START HERE</span><h2>A trip that fits <em>your day.</em></h2><p>A few details are all we need to get you moving.</p></div><span className="quick-stamp"><Sparkles size={20}/> NO ACCOUNT NEEDED</span></div><div className="quick-panel"><div className="quick-fields"><label>Trip length<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} {n===1?'day':'days'}</option>)}</select></label><label>Total budget<input type="number" min="500" step="100" value={budget} onChange={e=>setBudget(Math.max(500,Number(e.target.value)||500))}/></label><label>Travelers<select value={travelers} onChange={e=>setTravelers(Number(e.target.value))}>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n}>{n} {n===1?'person':'people'}</option>)}</select></label></div><div className="quick-bottom"><div><strong>I'm here for</strong><div className="interest-chips">{interests.filter(i=>['Nature','Food','Cafés','Culture','Views','Adventure','Shopping','Family'].includes(i)).map(i=><button type="button" className={`chip ${selected.includes(i)?'selected':''}`} aria-pressed={selected.includes(i)} key={i} onClick={()=>toggle(i)}>{i}</button>)}</div></div><button type="button" className="button button-dark quick-generate" onClick={go}>Generate my trip <ArrowUpRight size={18}/></button></div></div></section>
    <section className="section-muted"><div className="container discover-section"><div className="section-header"><div><span className="eyebrow">THE PLACES WE KEEP COMING BACK TO</span><h2>Start with the <em>favorites.</em></h2></div><Link className="text-link" to="/explore">Explore all places <ArrowUpRight size={17}/></Link></div><div className="destination-grid">{highlights.map(id=><DestinationCard key={id} destination={destinations.find(d=>d.id===id)!} compact/>)}</div></div></section>
    <section className="container experiences-section"><div className="experience-copy"><span className="eyebrow">MORE THAN A CHECKLIST</span><h2>Pick a feeling.<br/><em>We'll find the places.</em></h2><p>Maybe it's a slow walk through the pines, a fresh cup after the rain, or the first view that makes you stop in your tracks.</p><div className="experience-links">{[['The nature day','Nature'],['A little art & culture','Culture'],['The food wander','Food'],['Views worth the climb','Views']].map(([name,tag])=><Link key={tag} to={`/explore?category=${tag}`}><span>{name}</span><ArrowUpRight size={18}/></Link>)}</div></div><div className="experience-photo"><img src={destinations.find(d=>d.id==='camp-john-hay')!.image} alt="Pine trail at Camp John Hay" loading="lazy"/><div className="photo-caption"><span>01 / 04</span><strong>Find room to wander.</strong><small>Camp John Hay · Baguio City</small></div></div></section>
    <section className="weather-band"><div className="container weather-band-inner"><div><span className="eyebrow">KNOW BEFORE YOU GO</span><h2>Mountain weather has<br/><em>its own plans.</em></h2><p>Check Baguio's forecast while you plan. If rain rolls in, shift your day toward culture, cafés and covered stops.</p><Link className="text-link" to="/planner">Plan around the weather <ArrowUpRight size={17}/></Link></div><WeatherCard/></div></section>
    <section className="container how-section"><div className="section-header"><div><span className="eyebrow">SIMPLE BY DESIGN</span><h2>From idea to <em>itinerary.</em></h2></div></div><div className="steps">{[[<CalendarDays/>, '01','Tell us your plans','Choose your dates, budget, interests and how full you want each day.'],[<Sparkles/>, '02','Get a sensible route','Pinepath groups fitting places with time for travel and lunch.'],[<Route/>, '03','Make it your own','Swap a stop, see the route and watch the cost update.'],[<MapPinned/>, '04','Take it with you','Save, share or print your trip—no account required.']].map(([icon,n,title,body])=><div className="step" key={String(n)}><div className="step-icon">{icon}</div><span>{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className="container closing-section"><div><span className="eyebrow">YOUR MOUNTAIN DAYS START HERE</span><h2>Let the good days<br/><em>find their way.</em></h2></div><Link className="button button-light" to="/planner">Plan my trip <ArrowUpRight size={18}/></Link></section>
  </>
}
